main = "worker.ts"
name = "unity-r2-worker"
account_id = "4da06b8dd82a245849a974f3dcfc3365"
workers_dev = true
compatibility_date = "2025-06-01"

[[r2_buckets]]
bucket_name = "unity-builds"
binding = "unity_builds"
